# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get -y install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libgdal-dev bwidget libgdal-dev libgdal1-dev libgeos-dev libgeos++-dev libgsl0-dev libproj-dev libspatialite-dev netcdf-bin libgmp3-dev libudunits2-dev unzip wget

after_success:
  - wget -O /home/travis/R/Library/dismo/java/maxent.jar.zip "http://www.java2s.com/Code/JarDownload/maxent/maxent.jar.zip" & unzip /home/travis/R/Library/dismo/java/maxent.jar.zip -d /home/travis/R/Library/dismo/java/
  - Rscript -e 'covr::codecov()'
