## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: R
cache: packages

 include:
  - r: devel
  - r: release
    deploy:
      provider: script
      skip_cleanup: true
  - name: Strict Latin-1 locale
    r: release
    before_script:
      - sudo locale-gen en_US
      - export LC_ALL=en_US
  - name: Dev rlang and vctrs
    r: release
    r_github_packages:
      - marlonkobos/kuenm
